### ISSUE TITLE
Disconnecting issue

### ISSUE THREAD

**Issue by mspinolo** [eifinger/hass-foldingathomecontrol#34]
Being on version 2.0.8 and getting this repeatedly

```
Logger: custom_components.foldingathomecontrol
Source: custom_components/foldingathomecontrol/foldingathomecontrol_client.py:95 
Integration: Folding@HomeControl (documentation) 
First occurred: 20:18:13 (83 occurrences) 
Last logged: 20:38:58

Got disconnected from localhost:36330. Trying to reconnect.
```

it looks like there is an issue as it happens in a very short time period

```
2021-04-13 20:27:02 ERROR (MainThread) [custom_components.foldingathomecontrol] Got disconnected from localhost:36330. Trying to reconnect.
2021-04-13 20:27:17 ERROR (MainThread) [custom_components.foldingathomecontrol] Got disconnected from localhost:36330. Trying to reconnect.
2021-04-13 20:27:32 ERROR (MainThread) [custom_components.foldingathomecontrol] Got disconnected from localhost:36330. Trying to reconnect.
2021-04-13 20:27:47 ERROR (MainThread) [custom_components.foldingathomecontrol] Got disconnected from localhost:36330. Trying to reconnect.
2021-04-13 20:28:03 ERROR (MainThread) [custom_components.foldingathomecontrol] Got disconnected from localhost:36330. Trying to reconnect.
```

**Comment by eifinger** [comment]
It seems like the integration is working as expected. Somehow it looses connectivity but regains it again and looses it again.
You will only see the log message once when the client was connected before. So inbetween the log messages it was definately connected again.

Is your network dropping packages maybe because you are an wifi?

**Comment by mspinolo** [comment]
no, i am not: I am running Folding@home as add-on so I guess it should not disconnect as connection is happening within the same machine but across different docker container, isn't it?

Also I can't make it work the service call to pause or unpause the container: not sure if I am using the wrong syntax for it or is it due to the connection issue.

**Comment by eifinger** [comment]
This is indeed strange.
The services are not working in version 2.0.8 please use version 2.0.9

**Comment by mspinolo** [comment]
I can confirm services work on 2.0.9, just upgrade, did see issue #32

**Comment by nepozs** [comment]
I have the same issue with 2.0.9
additional problem looks like memory leak (I've confirmed - growing memory and processor usage is linked with working FAHControl)
![FAHControl_memory_leak_Screenshot_2021-04-15 Poziomo - Home Assistant](https://user-images.githubusercontent.com/56661567/114864349-2ba75d80-9df1-11eb-9441-7f18ba34ffbf.png)

additional information (but I haven't tested it in depth) - it looks like problem does not exist with system using YAML configuration, I've observed problems on systems where integration was added by integration GUI

```
Logger: custom_components.foldingathomecontrol
Source: custom_components/foldingathomecontrol/foldingathomecontrol_client.py:95
Integration: Folding@HomeControl (documentation)
First occurred: 14 kwietnia 2021, 20:41:16 (3613 occurrences)
Last logged: 13:44:27

Got disconnected from localhost:36330. Trying to reconnect.
```

**Comment by eifinger** [comment]
I had another idea, could you enable `debug` logging for `FoldingAtHomeControl` using the logger service:
https://www.home-assistant.io/integrations/logger/#service-set_level

The call should like like:

```yaml
service: logger.set_level
data:
  FoldingAtHomeControl: debug
````

**Comment by nepozs** [comment]
Yes i will do it in near future, but i had to configure test system, because integration eats all memory so it is impossible to do it on real "production" system.

**Comment by mspinolo** [comment]
I Can confirm I have the same memory leak & increasing with time avg CPU @nepozs reported.

Still disconnecting issues are present.
For the moment I disabled the integration

**Comment by nepozs** [comment]
```
Logger: homeassistant.components.sensor
Source: custom_components/foldingathomecontrol/foldingathomecontrol_device.py:16
Integration: Sensor (documentation, issues)
First occurred: 24 kwietnia 2021, 23:31:07 (1 occurrences)
Last logged: 24 kwietnia 2021, 23:31:07

Error while setting up foldingathomecontrol platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 205, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/foldingathomecontrol/sensor.py", line 42, in async_setup_entry
    async_add_sensors(
  File "/config/custom_components/foldingathomecontrol/sensor.py", line 24, in async_add_sensors
    FoldingAtHomeControlSensor(
  File "/config/custom_components/foldingathomecontrol/sensor.py", line 59, in __init__
    super().__init__(client, slot_id)
  File "/config/custom_components/foldingathomecontrol/foldingathomecontrol_device.py", line 16, in __init__
    self._device_name = f"{client.address} {client.slot_data[slot_id]['Description'].split(':')[0].upper()}: {slot_id}"  # pylint: disable=line-too-long
KeyError: 'Description'
```

**Comment by eifinger** [comment]
@nepozs thank you for your logs. I see that you editted your post, I did not get a notifcation for that.
Look like increasing your read timeout under the integration option will solve the problem as a fast fix.

I will however have to find out where the memleak ist.

**Comment by eifinger** [comment]
Not yet. I'm still setting up a test environment to reproduce the bug

**Comment by eifinger** [comment]
@mspinolo [v2.0.11](https://github.com/eifinger/hass-foldingathomecontrol/releases/tag/v2.0.11) will be released in a few minutes.

The issue should be resolved. I would be very glad if you could give it a try.

**Comment by nepozs** [comment]
@eifinger 
I have dedicated HA installation, so I will test it (today I've had power outage just after update, but I think, that everything will be OK).

I've tried increasing values (10x) in settings (with old version), but it didn't help a lot - it is my last week (in test environment):
![FAH_control_eating_resources_Screenshot_2021-05-05 Poziomo - Home Assistant](https://user-images.githubusercontent.com/56661567/117213475-f1334e00-adfb-11eb-97e8-052f087e76d4.png)
so the new version is my only hope.

**Comment by mspinolo** [comment]
Hi, 

still having disconnection issue, please see the log of the sensor:

![grab 2021-05-11 alle 20 18 08](https://user-images.githubusercontent.com/43354538/117865610-6c7e7f00-b296-11eb-8923-d27348afa315.png)

you can notice there is a different interval between disconnections: this is because i changed the update rate / default timeout to 30/60, before it was 5/15 as per default.
To me it looks like the integration is constantly connecting/disconnecting

**Comment by mspinolo** [comment]
I will confirm this in a few days but it looks like at a first glance nothing changed in terms of cpu/memory leakages

**Comment by eifinger** [comment]
[v2.0.13](https://github.com/eifinger/hass-foldingathomecontrol/releases/tag/v2.0.13) will be automatically released in a few minutes.
I included a heartbeat command which should fix the connection loss when the system is paused and not sending any status updates on its own.

**Comment by mspinolo** [comment]
v2.0.13 didn't have any leak, but I had a more serious issue: by no reason (at least I can find) couldn't connect anymore to folding@home (running in docker on HassOS).
Entities disappeared.

I tried to do a bit of everything removing integration, re-adding, starting container, etc...but nothing

**Comment by eifinger** [comment]
@mspinolo did you see anything in the logs?
When you readded the integration, did the authentication during the setup succeed?
Is your folding@home instance currently working on an assignment?

**Comment by mspinolo** [comment]
Ok so I understood a bit more: it is happening that everytime I update HA (running HassOS so running HA in docker) the component can't connenct anymore to Folding@Home (which in my case is running as add-on).

Workaround is to remove folding@home add-in and re-add it, then the custom components can connect again

**Comment by mspinolo** [comment]
Hi,

confirmed issue is still there: is there anything I can do to mitigate while being fixed?

**Comment by eifinger** [comment]
It's hard to recreate the issue and I am still setting up a test environment.
Did you see anything new in the logs during the updates when this happens?

**Comment by mspinolo** [comment]
no i didn't but it is very repeatable, although not happening on every restart of HA so I can't understand what the issue really is.

I am running HassOS in proxmox and F@H is running on HA official add-on.
Component is setup to connect to 127.0.0.1,, update rate is 30, timeout 60.

Please let me know if I can provide further information

**Comment by eifinger** [comment]
> Ok so I understood a bit more: it is happening that everytime I update HA (running HassOS so running HA in docker) the component can't connenct anymore to Folding@Home (which in my case is running as add-on).
> 
> Workaround is to remove folding@home add-in and re-add it, then the custom components can connect again

So you this happens **sometimes** when you restart HA?
And the "workaround" is to restart the F@H Addon? You are not removing and reading this custome_component?

**Comment by mspinolo** [comment]
yes, the workaround is to **remove** and re-add the addon.
Restarting the add-on doesn't work.

Nothing done on the custom_component

**Comment by eifinger** [comment]
Okay I set up a test environment. Now I will try to make it crash^^

**Comment by eifinger** [comment]
My testenvironment did not crash a single time. I cannot reproduce the issue.

**Comment by mspinolo** [comment]
That is very strange… I added a second PC in my system running folding at home and connected to HA by this integration.

Also for this exact same behavior: upon HA restart sometimes it is not connecting anymore and lead to “unavailable” state for all sensors.

monouso thing I changed is the update rate and timeout to 30/60: can this lead to issues?

**Comment by eifinger** [comment]
The update rate should be higher than the timeout rate so this should be fine.
I still did not have a single restart where I experience "unavailable" states.

Have you already tried the newest version?

**Comment by mspinolo** [comment]
Yes, I am on latest: still having issues.

i am running HassOS into proxmox: could it be the reason?

**Comment by eifinger** [comment]
I have the same setup.
Old Laptop with Proxmos installed. A single VM running HassOS. Using the Folding@Home Addon.

Any new insights regarding logs?

**Comment by eifinger** [comment]
It finally happened. All sensors went to unavailable. Not during a restart. Just happened.

**Comment by eifinger** [comment]
@mspinolo I just released version v2.2.0
Along with implementing the button and select platform I added additional debug logging.

Since you experience the disconnects more often than me, could you enable the same debug levels?

My config in `configuration.yaml` is

```yaml
logger:
  default: info
  logs:
    FoldingAtHomeControl.foldingathomecontrol: debug
    custom_components.foldingathomecontrol: debug
````
(Needs a restart to take effect)

**Comment by eifinger** [comment]
@mspinolo I figured out that the Server was not always sending the data the integration was requesting. I built in a forced update and this should fix this issue.
Please feel free to reopen if it still exists!
